name: Amirhossein Zareian
author: Amirhossein Zareian
description: Developer | Linux | agnostic
avatar: /images/logo.jpg

footer-links:
  dribbble:
  email: amirhosseinzareian01@gmail.com
  facebook:
  flickr:
  github: AmirHossein-z
  instagram:
  linkedin: amirhossein-zareian
  telegram: Amirhosseyn_Zareian
  pinterest:
  medium: Amirhossein_Zareian
  rss: rss
  twitter:
  stackoverflow:
  youtube:
  googleplus:
  playconsole:
  mastodon:

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: Amirhossein Zareian

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# For newer "GA4" analytics, use the following instead of the "UA" entry above
#google_analytics_ga4: G-GABC1DEFG

# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: https://amirhossein-z.github.io
enforce_ssl: https://amirhossein-z.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

sass:
  style: :expanded # You might prefer to minify using :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

include: ["_pages"]

paginate: 6
paginate_path: /page:num/

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
